services:
  python_app:
    build: .
    container_name: chariot_app
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      mysql_db:
        condition: service_healthy
      postgres_db:
        condition: service_healthy
      neo4j_db:
        condition: service_healthy
    networks:
      - chariot_network

  mysql_db:
    image: mysql:8.0
    container_name: chariot_mysql
    command: --local_infile=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql-files
    networks:
      - chariot_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db:
    image: postgres:16
    container_name: chariot_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chariot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - chariot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j_db:
    image: neo4j:5.26
    container_name: chariot_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - chariot_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  chariot_network:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
  neo4j_data:
