services:
  python_app:
    build: .
    container_name: chariot_app
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mysql_db
      - postgres_db
      - neo4j_db
    networks:
      - chariot_network

  mysql_db:
    image: mysql:8.0
    container_name: chariot_mysql
    command: --local_infile=1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chariot_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql-files
    networks:
      - chariot_network

  postgres_db:
    image: postgres:16
    container_name: chariot_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chariot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chariot_network

  neo4j_db:
    image: neo4j:5.26
    container_name: chariot_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - chariot_network

networks:
  chariot_network:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
  neo4j_data:
